# Generated by Django 3.0.3 on 2022-11-15 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carComm_app', '0003_listing_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='Listing',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
