# Generated by Django 4.1.3 on 2022-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carComm_app', '0004_auto_20221115_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='pendingSale',
            field=models.BooleanField(default=False),
        ),
    ]
