# Generated by Django 4.1.3 on 2022-12-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carComm_app', '0005_queries_listing_pendingsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='pendingSale',
            new_name='pending_sale',
        ),
    ]
